todo/urls.py
from django.urls import path
from .views import * 
app_name = 'todo'

urlpatterns = [
    path('', home, name='home'),
    path('currenttodos', currenttodos, name = 'currenttodos' ),
    path('createtodo', createtodo, name = 'createtodo'),
    path('completedtodo', completedtodo, name = 'completedtodos'),
    path('viewtodo/<int:todo_pk>', viewtodo, name = 'viewtodo'),
    path('viewtodo/<int:todo_pk>/complete', completetodo, name = 'completetodo'),
    path('viewtodo/<int:todo_pk>/delete', deletetodo, name = 'deletetodo')
]

todowoo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    ##auth
    path('', include('user.urls')),
    ##todos
    path('', include('todo.urls')),
]

user/urls.py
from django.urls import path
from .views import *
app_name = 'user'

urlpatterns = [
    path("signup/", signupuser, name='signupuser'),
    path('logout', logoutuser, name= 'logoutuser'),
    path('login', loginuser, name= 'loginuser'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length = 100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null = True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Todo_list(models.Model):
    title = models.CharField(max_length = 100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null = True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

todo/forms.py
from django.forms import ModelForm
from .models import Todo_list
class TodoForm(ModelForm):
    class Meta:
        model = Todo_list
        fields = ['title', 'memo', 'important']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import TodoForm
from .models import Todo_list
from django.utils import timezone
from django.contrib.auth.decorators import login_required
#Create your views here.
def home(request):
    return render(request, 'todo/home.html')

@login_required
def currenttodos(request):
    alltodos = Todo_list.objects.filter(user = request.user, datecompleted__isnull=True)
    return render(request, 'todo/currenttodos.html', {'todos':alltodos})

@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form':TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('todo:currenttodos')
        except ValueError:
             return render(request, 'user/createtodo.html', {'form':TodoForm(), 'error':'Invalid Data Passed. Try again!'})        

@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo_list, pk = todo_pk, user = request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo':todo, 'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
             return render(request, 'user/viewtodo.html', {'form':TodoForm(), 'error':'Invalid Data Passed. Try again!'})       
@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo_list, pk = todo_pk, user = request.user)
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')
    
@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo_list, pk = todo_pk, user = request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')


@login_required
def completedtodo(request):
    alltodos = Todo_list.objects.filter(user = request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'todo/completedtodo.html', {'todos':alltodos})

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
# Create your views here.
def signupuser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            try:
                user = User.objects.create_user(username=username, password = password1)
                user.save()
                login(request, user)
                return redirect('todo:currenttodos')
            except IntegrityError:
                return render(request, 'user/signup.html', {'form':UserCreationForm(), 'error':'Username already taken'})
        else:
            return render(request, 'user/signup.html', {'form':UserCreationForm(), 'error':'Passwords do not match'})
        print(username)
        return redirect('todo:home')
    else:
        return render(request, 'user/signup.html', {'form':UserCreationForm()})

def logoutuser(Request):
    logout(Request)
    return redirect('todo:home')

def loginuser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            return redirect('todo:home')
        else:
            return render(request, 'user/signin.html', {'form':AuthenticationForm(), 'error':'Invalid Credentials'})        
        return redirect('todo:home')
    else:
        return render(request, 'user/signin.html', {'form':AuthenticationForm()})

todo/templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png"  href="{% static 'todo/logo.png' %}">
    <title>Todo Woo</title>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <a class="navbar-brand" href="{% url 'todo:home' %}">
         <img src="{% static 'todo/logo.png' %}" width="30" height="30" class="d-inline-block align-top">
        <span>Todo Woo</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">

                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
                </li>
                <li class="nav-item {{ completed }}">
                    <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
                </li>
                <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
                </li>

        </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'user:logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:signupuser' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:loginuser' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/completedtodo.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <h1>Completed Todos</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:viewtodo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b> - Completed {{ todo.datecompleted|date:'M j Y H:i' }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/createtodo.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" id="title" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo</label>
                    <textarea name="memo" class="form-control" id="memo" ></textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important">
                    <label class="form-check-label" for="important">Important</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

todo/templates/todo/currenttodos.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if todos %}
                 <h1>{{ todos.count }} Current Todo{{ todos.count|pluralize }}</h1>
            {% else %}
                           <h1>Current Todos</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if todos %}
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:viewtodo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %}</a>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center">
                <h2>Looks like you don't have any todos! Nice work.</h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'todo:createtodo' %}">New Todo</a>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

todo/templates/todo/home.html
{% extends "todo/base.html" %}

{% block content %}
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Simply Your Todos. Woo!</h1>
            <p>Life is fun. But life is also busy. There's a million different things you could be doing. But what matters is <u>what</u> you do. We created <b><i>Todo Woo</i></b> to help you make sense of all of your opportunities and live that life that matters most to you. Your new organized life awaits.</p>
        <a role="button" class="btn btn-primary btn-lg" href="{% url 'user:signupuser' %}">Start</a>
        </div>
    </div>

{% endblock %}

todo/templates/todo/viewtodo.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo</label>
                    <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important" {% if todo.important %}checked{% endif %}>
                    <label class="form-check-label" for="important">Important</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-success" onclick="$('#complete').click()">Complete</button>
                <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Delete</button>
            </form>
        </div>
    </div>
    {% if todo.datecompleted is None %}
        <form style='display: none;' method="POST" action="{% url 'todo:completetodo' todo.id %}">
            {% csrf_token %}
            <button id="complete" type="submit">Complete</button>
        </form>
    {% endif %}
    <form style='display: none;' method="POST" action="{% url 'todo:deletetodo' todo.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
{% endblock %}

user/templates/user/signin.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'user:signupuser' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/signup.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'user:loginuser' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}